### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by dannilo18** [dannilo18/actives#5]
# Menu 1
- [x] load active types https://github.com/dannilo18/actives/issues/6;
- [x] list and select active type https://github.com/dannilo18/actives/issues/7;
- [x] add/delete active type https://github.com/dannilo18/actives/issues/8;
- [x] quit.

# Menu 2
- [x] select active https://github.com/dannilo18/actives/issues/9;

# Menu 3
Depending on active type, the third menu can change, but some functions will be the same:
- [x] create active file;
   - [x] ship
- [ ] show info;
- [ ] show apport historic;
- [ ] add new apport.
## Criptocurrencies
- [ ]
